### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by RogMoe** [pvyleta/ebusd-brink-hru#1]
I own a Brink Renovent Excellent 300+ with sw version S1.06.08 0007 and a Brink Air Control wall module, sw version S2.01.09

Questions:
**Wich config file should I use?**
I tried the Dutch version Excellent300.10608.10706.plus.csv but I'm  missing a few parameters in Home Assistant, such as Bypass Hystereses ,Set Bypass Mode, 0-10vSettings, UnbalanceMode amongst others.

For some reasons settings are read-only. If a change Ventilator Mode, it changes back to its previous setting. Same goes for a few other settings.

What am I doing wrong?

**Comment by pvyleta** [comment]
Greetings to Netherlands!

>  I'm missing a few parameters in Home Assistant

Very likely the cause is the `mqtt-hassio.cfg`. Read through it, there is parameter `filter-name` - likely you need to set it to filter out the dutch names of parameters, for simplicity just type in `*`.

Regarding the ventilator mode, with the connected Air Control Module that cannot be achieved, as the air control module remembers the value set on its own, and force-sends it to the HRU every +-5 seconds. I fiddled with this for a long long time, and unfortunately my only solutions is either:
a. Change flow rate of currently selected flow mode (but I am not sure if changing this too often will not wear out the persistend memory on teh unit over few years), or
b. Do not use the Air Control at all, since after you set the automation to your liking in Home assistant, you realise you do not need it anymore.

**Comment by RogMoe** [comment]
Greetings to the Czech Republic!

I suspected the mqtt file to be the culprit too, but wasn't sure what to edit. I'll give it a try one of these days.
We come to the same conclusion. I was thinking about the problem while staring at a blincking LED on the ebus-adapter. Then I realised the Air Control was sending out (the same) data every x-seconds! I prefer to keep the Air Control beacuse it has a high WAF... hahaha. My initial idea is to control the machine by Home Assistant. I could make a few external buttons using an ESP.
The proper solution would be to manipulate the Air Controler by ebus, but no one seems to have done this before...

Thanks Petr!

**Comment by pvyleta** [comment]
>The proper solution would be to manipulate the Air Controler by ebus, but no one seems to have done this before...

I tried looking into it with no success. I was able to decode few messages for Air Control as well, but it just refuses to talk to ebusd on its slave address. I suspect some proprietary stuff. 

But my experience is, that after you get comfortable with home assistant, you do not really need the Air Control anymore. I am now controlling my HRU based on co2 levels automatically, and do not ever have a need to adjust it manually anymore.

btw with the mqtt-hassio.cfg, I suggest checking if you have the paths correctly set up in the ebusd addon vs. where your file physically lives.

**Comment by RogMoe** [comment]
Okay, I'll sell the Air Controler and stick with HA.
Everything is working fine now. Skipped all irrelevant settings to speed up things and did some additional translating from the config. **Thanks for all your work!**
![BrinkHA](https://github.com/pvyleta/ebusd-brink-hru/assets/74535064/db15995e-51b0-4016-b547-e312cf18a642)
